const filmes = [
  'https://www.youtube.com/watch?v=BqMdQBox15s',
  'https://www.youtube.com/watch?v=nZv5URKTM8k',
  'https://www.youtube.com/watch?v=9Lwepn1v3Xo',
  'https://www.youtube.com/watch?v=ybfRLnWZQ0g',
  'https://www.youtube.com/watch?v=605-iwPa8ck',
  'https://www.youtube.com/watch?v=OrEFA5fTOx0',
  'https://www.youtube.com/watch?v=6xLJYCI99mk',
  'https://www.youtube.com/watch?v=Bic8g7raeJQ',
  'https://www.youtube.com/watch?v=Bp8CDnvmE00',
  'https://www.youtube.com/watch?v=T5FlDy3YmDQ',
  'https://www.youtube.com/watch?v=SpOvINodAAE',
  'https://www.youtube.com/watch?v=gSo7ekXg4YI',
  'https://www.youtube.com/watch?v=VHHwf7eAH0I',
  'https://www.youtube.com/watch?v=t-r8mhZH11o',
  'https://www.youtube.com/watch?v=5RrWE7t7_NU',
  'https://www.youtube.com/watch?v=poLPKdc-zTY',
  'https://www.youtube.com/watch?v=LtxiokrYpxw',
  'https://www.youtube.com/watch?v=jS6kAKj8R9o',
  'https://www.youtube.com/watch?v=erR1dgyv1_U',
  'https://www.youtube.com/watch?v=Qs7xS-UgWcg',
  'https://www.youtube.com/watch?v=rtn4-lDSB80',
  'https://www.youtube.com/watch?v=luylsO8UlhE',
  'https://www.youtube.com/watch?v=Gk_2euKF9MY',
  'https://www.youtube.com/watch?v=SmMmQHR_F4Y',
  'https://www.youtube.com/watch?v=b1jqSRnqLMw',
  'https://www.youtube.com/watch?v=m8LWjDS3IkQ',
  'https://www.youtube.com/watch?v=1jEe_vPgNJE',
  'https://www.youtube.com/watch?v=O1-lkTgl-ws',
  'https://www.youtube.com/watch?v=w80ZSg7kNbE',
  'https://www.youtube.com/watch?v=ymA7OFZ9lF0',
  'https://www.youtube.com/watch?v=43OVm86-4rU',
  'https://www.youtube.com/watch?v=JOBYJrVQm3A',
  'https://www.youtube.com/watch?v=WTMcikRZcBk',
  'https://www.youtube.com/watch?v=-0f67QE-HP8',
  'https://www.youtube.com/watch?v=dXBUdCvqpNg',
  'https://www.youtube.com/watch?v=diteeSODzTQ',
  'https://www.youtube.com/watch?v=t_NZNgm66xI',
  'https://www.youtube.com/watch?v=8qaAKxJp0EM',
  'https://www.youtube.com/watch?v=56fngopihOo',
  'https://www.youtube.com/watch?v=XfBImxhVWTw',
  'https://www.youtube.com/watch?v=gGz0wTHCHK4',
  'https://www.youtube.com/watch?v=aGFgiXok1iQ',
  'https://www.youtube.com/watch?v=VyydT8dy3Hs',
  'https://www.youtube.com/watch?v=8QJiAK-s5a0',
  'https://www.youtube.com/watch?v=sOBIrjgDZr4',
  'https://www.youtube.com/watch?v=1dwtsZ4IJQE',
  'https://www.youtube.com/watch?v=YAmnMBHMPso',
  'https://www.youtube.com/watch?v=ZNn6J56J5HE',
  'https://www.youtube.com/watch?v=7OIn2KFDWjM',
  'https://www.youtube.com/watch?v=ILqwaOR70mU',
  'https://www.youtube.com/watch?v=sOBIrjgDZr4',
  'https://www.youtube.com/watch?v=5Ui9rRepv0Q',
  'https://www.youtube.com/watch?v=-wI4jJq98tU',
  'https://www.youtube.com/watch?v=1dwtsZ4IJQE',
  'https://www.youtube.com/watch?v=7OIn2KFDWjM',
  'https://www.youtube.com/watch?v=YAmnMBHMPso',
  'https://www.youtube.com/watch?v=6MaOE8YiJy8',
  'https://www.youtube.com/watch?v=UqPRk4oFz_U',
  'https://www.youtube.com/watch?v=ZNn6J56J5HE',
  'https://www.youtube.com/watch?v=diteeSODzTQ',
  'https://www.youtube.com/watch?v=hIJ0gMDZT_4',
  'https://www.youtube.com/watch?v=3lX50Lh2Iec',
  'https://www.youtube.com/watch?v=9VsHtn_RSHY',
  'https://www.youtube.com/watch?v=h_bUcNjmuSk',
  'https://www.youtube.com/watch?v=gV6Y3OwR2n0',
  'https://www.youtube.com/watch?v=ILqwaOR70mU',
  'https://www.youtube.com/watch?v=G7gklW3Xbn8',
  'https://www.youtube.com/watch?v=x4L81QLGYuM',
  'https://www.youtube.com/watch?v=WJOMiXmwfYE',
  'https://www.youtube.com/watch?v=ElvTXO2A3Uw',
  'https://www.youtube.com/watch?v=8osP7KRacWk',
  'https://www.youtube.com/watch?v=GP1KHL0j0GU',
  'https://www.youtube.com/watch?v=YCN_nis2E84',
  'https://www.youtube.com/watch?v=2dn_r_sgBEE',
  'https://www.youtube.com/watch?v=kMkxtj-mu14',
  'https://www.youtube.com/watch?v=En7TapBA84M',
  'https://www.youtube.com/watch?v=_y_We1FV_RQ',
  'https://www.youtube.com/watch?v=FYDrPt06XNI',
  'https://www.youtube.com/watch?v=7xUtZzLBV5c',
  'https://www.youtube.com/watch?v=MFd88DSTPgI',
  'https://www.youtube.com/watch?v=6ohgHjQvK5g',
  'https://www.youtube.com/watch?v=RJjhiIlRzw0',
  'https://www.youtube.com/watch?v=AhZw2QXKT1A',
  'https://www.youtube.com/watch?v=Qgrff5fpRRg',
  'https://www.youtube.com/watch?v=Jy8mz4gu2oQ',
  'https://www.youtube.com/watch?v=bBil15ORYI0',
  'https://www.youtube.com/watch?v=IlH-egwG2pQ',
  'https://www.youtube.com/watch?v=Bwpvq4JhqY4',
  'https://www.youtube.com/watch?v=xRShAxpUZ6Y',
  'https://www.youtube.com/watch?v=qVNAGVSKEBQ',
  'https://www.youtube.com/watch?v=uPAXLQIxBGY',
  'https://www.youtube.com/watch?v=uAjGtAOqMQw',
  'https://www.youtube.com/watch?v=Mp5IvPj4ay0',
  'https://www.youtube.com/watch?v=JRpouK0KmWQ',
  'https://www.youtube.com/watch?v=t9BqiLLt9SI',
  'https://www.youtube.com/watch?v=cnQEo4bazIo',
  'https://www.youtube.com/watch?v=eMR4FoLvb9A',
  'https://www.youtube.com/watch?v=DmXp6Pm-uLI',
  'https://www.youtube.com/watch?v=7BwxSHs9elk',
  'https://www.youtube.com/watch?v=-oL4NpO7eAw',
  'https://www.youtube.com/watch?v=50N2eB0JI80',
  'https://www.youtube.com/watch?v=AtJ5phl1iVE',
  'https://www.youtube.com/watch?v=q-H62GgHjeg',
  'https://www.youtube.com/watch?v=UY0nYr-dXEI',
  'https://www.youtube.com/watch?v=hT_CiaTcnN8',
  'https://www.youtube.com/watch?v=1TqRcAl_928',
  'https://www.youtube.com/watch?v=NkaJFlr5Fhk',
  'https://www.youtube.com/watch?v=V-9fQTUix6I',
  'https://www.youtube.com/watch?v=azvRjKHhpfA',
  'https://www.youtube.com/watch?v=gZY_zy2hAHA',
  'https://www.youtube.com/watch?v=g5AixBKy7b4',
  'https://www.youtube.com/watch?v=vRUQ_q5mivc',
  'https://www.youtube.com/watch?v=qDR_yTik_xo',
  'https://www.youtube.com/watch?v=mbTKo5Ylypw',
  'https://www.youtube.com/watch?v=86Vd7XFiYZA',
  'https://www.youtube.com/watch?v=9W7Ifu4OrvQ',
  'https://www.youtube.com/watch?v=0vv4ycVEVF4',
  'https://www.youtube.com/watch?v=lDRzG3mH-DQ',
  'https://www.youtube.com/watch?v=yQpFQFL-YLI',
  'https://www.youtube.com/watch?v=z7coL1WcCoI',
  'https://www.youtube.com/watch?v=mwMmZ8dtWNM',
  'https://www.youtube.com/watch?v=xGj_wbPl-6w',
  'https://www.youtube.com/watch?v=uuNy1Ibdk_Y',
  'https://www.youtube.com/watch?v=PFbxA5HjwyQ',
  'https://www.youtube.com/watch?v=bu9YxTb6gf8',
  'https://www.youtube.com/watch?v=3dluAhOU1cA',
  'https://www.youtube.com/watch?v=uhpknFQJ7G0',
  'https://www.youtube.com/watch?v=I8-3VpZrBww',
  'https://www.youtube.com/watch?v=mQJPI9_TVHA',
  'https://www.youtube.com/watch?v=0u5O2--9www',
  'https://www.youtube.com/watch?v=opCf3mp24dE',
  'https://www.youtube.com/watch?v=zzUYkxN11P4',
  'https://www.youtube.com/watch?v=Omdvu0f-Wuw',
  'https://www.youtube.com/watch?v=NnDKut3pxoU',
  'https://www.youtube.com/watch?v=a3bI7kbVBwM',
  'https://www.youtube.com/watch?v=2GLDqvA6tKI',
  'https://www.youtube.com/watch?v=ts4gt7f_rek',
  'https://www.youtube.com/watch?v=9EV3DKPo-4U',
  'https://www.youtube.com/watch?v=Uv4YAx1nqDM',
  'https://www.youtube.com/watch?v=cmkZeTX5fq0',
  'https://www.youtube.com/watch?v=0_pN-X7Gew8',
  'https://www.youtube.com/watch?v=wf-gIUYRCyk',
  'https://www.youtube.com/watch?v=AMQgbNK7fGs',
  'https://www.youtube.com/watch?v=R_8AwlEdClA',
  'https://www.youtube.com/watch?v=3aSdLAndoJU',
  'https://www.youtube.com/watch?v=_kD54-q1uFM',
  'https://www.youtube.com/watch?v=vsfjzfGZVyQ',
  'https://www.youtube.com/watch?v=SYffGozxMbU',
  'https://www.youtube.com/watch?v=V25QF11MwDU',
  'https://www.youtube.com/watch?v=IqJWWBRnrH4',
  'https://www.youtube.com/watch?v=e96_1NxL9no',
  'https://www.youtube.com/watch?v=RgHtBxOs4qw',
  'https://www.youtube.com/watch?v=6I5B0jyLBUg',
  'https://www.youtube.com/watch?v=zQTDoxrgBeU',
  'https://www.youtube.com/watch?v=HVlrXQ3qWqo',
  'https://www.youtube.com/watch?v=9ExnVKy8hao',
  'https://www.youtube.com/watch?v=rx4sKoITt-Q',
  'https://www.youtube.com/watch?v=0osA8jKKotc',
  'https://www.youtube.com/watch?v=_uwVIMdk7hc',
  'https://www.youtube.com/watch?v=U0YkPnwoYyE',
  'https://www.youtube.com/watch?v=njz1p35e_EU',
  'https://www.youtube.com/watch?v=awkGgPALfho',
  'https://www.youtube.com/watch?v=KIAzalQUui4',
  'https://www.youtube.com/watch?v=QMBLWE0pu8U',
  'https://www.youtube.com/watch?v=DHVyayHXOdY',
  'https://www.youtube.com/watch?v=BGEFW4kc5EQ',
  'https://www.youtube.com/watch?v=v0KOJWyR4SU',
  'https://www.youtube.com/watch?v=IhTgiNhfF7k',
  'https://www.youtube.com/watch?v=fgbjvvCPa88',
  'https://www.youtube.com/watch?v=-ZxtmDbqDRc',
  'https://www.youtube.com/watch?v=C9PYzGyIfF8',
  'https://www.youtube.com/watch?v=yquyze0QbPk',
  'https://www.youtube.com/watch?v=bEBQWhgGM1g',
  'https://www.youtube.com/watch?v=rDGRAHBojWE',
  'https://www.youtube.com/watch?v=chBVj94zYDM',
  'https://www.youtube.com/watch?v=aF3x3Bad2Wk',
  'https://www.youtube.com/watch?v=RE9FX2YWRJQ',
  'https://www.youtube.com/watch?v=g425SDBoDBI',
  'https://www.youtube.com/watch?v=psB3Ta-5XWY',
  'https://www.youtube.com/watch?v=KA2ziAAXoqE',
  'https://www.youtube.com/watch?v=3Y-pMJ4IcTY',
  'https://www.youtube.com/watch?v=KEc0SGkBDJ4',
  'https://www.youtube.com/watch?v=T5d-R7FDG7s',
  'https://www.youtube.com/watch?v=qUammhHxd1k',
  'https://www.youtube.com/watch?v=eH7EyPs_Va8',
  'https://www.youtube.com/watch?v=PGy7bpf9ibo',
  'https://www.youtube.com/watch?v=P94mqkWtfxU',
  'https://www.youtube.com/watch?v=idvqLiOeLgc',
  'https://www.youtube.com/watch?v=-kFJKQvCrkY',
  'https://www.youtube.com/watch?v=aak6BqNR150',
  'https://www.youtube.com/watch?v=lX9SDbhnYYU',
  'https://www.youtube.com/watch?v=zZK_bkxhJes',
  'https://www.youtube.com/watch?v=ba2VaalmijM',
  'https://www.youtube.com/watch?v=LBBni_-tMNs',
  'https://www.youtube.com/watch?v=rDTZ6A5zsYc',
  'https://www.youtube.com/watch?v=lYCq6x3AHYw',
  'https://www.youtube.com/watch?v=rUmzIsaHTY4',
  'https://www.youtube.com/watch?v=TQCgzi4j3eM',
  'https://www.youtube.com/watch?v=OxLmmTv6CTs',
  'https://www.youtube.com/watch?v=HfgFZz6gCOM',
  'https://www.youtube.com/watch?v=74M0hPAeFHs',
  'https://www.youtube.com/watch?v=3cEg2HCl50I',
  'https://www.youtube.com/watch?v=tp1eVLXEXm8',
  'https://www.youtube.com/watch?v=5RKld6BGJA4',
  'https://www.youtube.com/watch?v=S5-Beq8JVsw',
  'https://www.youtube.com/watch?v=Ls2be_G7bHc',
  'https://www.youtube.com/watch?v=YNZmZ4ARr38',
  'https://www.youtube.com/watch?v=yWSRVYU_JMo',
  'https://www.youtube.com/watch?v=SN8hW7AeoQI',
  'https://www.youtube.com/watch?v=39mBogAVAQc',
  'https://www.youtube.com/watch?v=Z2xooz6844k',
  'https://www.youtube.com/watch?v=DGABqdbtQnA',
  'https://www.youtube.com/watch?v=sR528E5_8yI',
  'https://www.youtube.com/watch?v=F5GWqOrzQ3g',
  'https://www.youtube.com/watch?v=Pt6VzQ_0k_I',
  'https://www.youtube.com/watch?v=jn8SVc374U0',
  'https://www.youtube.com/watch?v=PSZxmZmBfnU',
  'https://www.youtube.com/watch?v=xzBC35K-vug',
  'https://www.youtube.com/watch?v=cPVM14Bnf5I',
  'https://www.youtube.com/watch?v=Kc9lVbz_-_o',
  'https://www.youtube.com/watch?v=f6DDYCf80hw',
  'https://www.youtube.com/watch?v=CyJglP6k8lE',
  'https://www.youtube.com/watch?v=ZHRWbydTGrI',
  'https://www.youtube.com/watch?v=2V_LmUEtPMs',
  'https://www.youtube.com/watch?v=O7why8Xo_RQ',
  'https://www.youtube.com/watch?v=hw3lBV-89M0',
  'https://www.youtube.com/watch?v=0GCwhGQEZ90',
  'https://www.youtube.com/watch?v=TGoICPqXjAY',
  'https://www.youtube.com/watch?v=7hsAbjmNpKU',
  'https://www.youtube.com/watch?v=foV6LGohzBI',
  'https://www.youtube.com/watch?v=1_-RGLVHmOA',
  'https://www.youtube.com/watch?v=DKtjBqJ4NxA',
  'https://www.youtube.com/watch?v=GSu7BGbyJqc',
  'https://www.youtube.com/watch?v=b0KSEziycmw',
  'https://www.youtube.com/watch?v=3H0V4XiAyv8',
  'https://www.youtube.com/watch?v=UXldWskFeFY',
  'https://www.youtube.com/watch?v=iNg7uRYtqLA',
  'https://www.youtube.com/watch?v=czzH5M2bUYc',
  'https://www.youtube.com/watch?v=qIxHb7cA6tg',
  'https://www.youtube.com/watch?v=1PwmcgK9qno',
  'https://www.youtube.com/watch?v=Qbnv6eHKjCQ',
  'https://www.youtube.com/watch?v=KYa1IsxGVuc',
  'https://www.youtube.com/watch?v=sFW-yxe13lo',
  'https://www.youtube.com/watch?v=0pgWUvW97ek',
  'https://www.youtube.com/watch?v=Wg89Bj_9Wg4',
  'https://www.youtube.com/watch?v=SEWMcT6bIi8',
  'https://www.youtube.com/watch?v=KhS2-vKr1JY',
  'https://www.youtube.com/watch?v=4M2WTfCDtyU',
  'https://www.youtube.com/watch?v=zvtUrjfnSnA',
  'https://www.youtube.com/watch?v=ZoL1epfoq-g',
  'https://www.youtube.com/watch?v=Iy2kMtJa2q8',
  'https://www.youtube.com/watch?v=PCn1uAs_0VQ',
  'https://www.youtube.com/watch?v=wWRnv1V8iUY',
  'https://www.youtube.com/watch?v=OjDuQ7O9XUo',
  'https://www.youtube.com/watch?v=TKybm_hdKTA',
  'https://www.youtube.com/watch?v=-qG1Hke8w_8',
  'https://www.youtube.com/watch?v=C0H2SnzitoM',
  'https://www.youtube.com/watch?v=Pojd3KNQq68',
  'https://www.youtube.com/watch?v=HXmru6NrSAY',
  'https://www.youtube.com/watch?v=_RG8hoGMxKw',
  'https://www.youtube.com/watch?v=Nfrk2UdEOcQ',
  'https://www.youtube.com/watch?v=wwnqJH8OF-I',
  'https://www.youtube.com/watch?v=zy8dUJEOqos',
  'https://www.youtube.com/watch?v=WZ6JK1mPT-A',
  'https://www.youtube.com/watch?v=WDuIl_uPY_s',
  'https://www.youtube.com/watch?v=Qbnv6eHKjCQ',
  'https://www.youtube.com/watch?v=f-3Bldu8BJ4',
  'https://www.youtube.com/watch?v=7o40za1wAlI',
  'https://www.youtube.com/watch?v=UayJYYeMANA',
  'https://www.youtube.com/watch?v=SY40M1lhknY',
  'https://www.youtube.com/watch?v=mIGCgzqFR0s',
  'https://www.youtube.com/watch?v=UZb2NOHPA2A',
  'https://www.youtube.com/watch?v=GDHVi3h6ZXw',
  'https://www.youtube.com/watch?v=S7OWoc-j8qQ',
  'https://www.youtube.com/watch?v=qRQu4tZF1GA',
  'https://www.youtube.com/watch?v=1IaDQdo8x1I',
  'https://www.youtube.com/watch?v=0ONU_H0EjIg',
  'https://www.youtube.com/watch?v=CWS1CWSAmjs',
  'https://www.youtube.com/watch?v=zkRkL94VQxY',
  'https://www.youtube.com/watch?v=XeO3jMZphhs',
  'https://www.youtube.com/watch?v=LzJ1fo-oUpk',
  'https://www.youtube.com/watch?v=rMS4ESFlfDk',
  'https://www.youtube.com/watch?v=_pWx7N8gSoY',
  'https://www.youtube.com/watch?v=Itr0jcR0S4s',
  'https://www.youtube.com/watch?v=rqS6CaouXwE',
  'https://www.youtube.com/watch?v=7EcK-LuhzAA',
  'https://www.youtube.com/watch?v=_AgBIeTHzTM',
  'https://www.youtube.com/watch?v=iwfU4ei5gWE',
  'https://www.youtube.com/watch?v=CMfYaFpa3nY',
  'https://www.youtube.com/watch?v=me9Vweatkto',
  'https://www.youtube.com/watch?v=6s8ZEFUSYAI',
  'https://www.youtube.com/watch?v=Y9b8tw9TR2k',
  'https://www.youtube.com/watch?v=BXlYuaycRbU',
  'https://www.youtube.com/watch?v=uuWIaDATbnE',
  'https://www.youtube.com/watch?v=AhbCYVILusc',
  'https://www.youtube.com/watch?v=LPPJdOGshUM',
  'https://www.youtube.com/watch?v=VbP7jMN_v-w',
  'https://www.youtube.com/watch?v=WVxVM2Lo5NM',
  'https://www.youtube.com/watch?v=o7WSgC9oGic',
  'https://www.youtube.com/watch?v=9WpO5zPo8Dg',
  'https://www.youtube.com/watch?v=bOR38552MJA',
  'https://www.youtube.com/watch?v=C0KLb_v50-k',
  'https://www.youtube.com/watch?v=iB25eDhWImc',
  'https://www.youtube.com/watch?v=8ty1025m6XQ',
  'https://www.youtube.com/watch?v=B0vKK-4qJac',
  'https://www.youtube.com/watch?v=zJMCctR8ivc',
  'https://www.youtube.com/watch?v=Cht63QybtiA',
  'https://www.youtube.com/watch?v=xYIhxXt58uE',
  'https://www.youtube.com/watch?v=5lBfYlWmDC8',
  'https://www.youtube.com/watch?v=5BLZxhN2lDE',
  'https://www.youtube.com/watch?v=u2D0kDFKaxE',
  'https://www.youtube.com/watch?v=qS2Np6zxXm0',
  'https://www.youtube.com/watch?v=PJlmYh27MHg',
  'https://www.youtube.com/watch?v=9rTcIUk9Aio',
  'https://www.youtube.com/watch?v=TQXuazYI_YU',
  'https://www.youtube.com/watch?v=lkMilWJJR_U',
  'https://www.youtube.com/watch?v=YhSKk-cvblc',
  'https://www.youtube.com/watch?v=rLZ5aVNxV84',
  'https://www.youtube.com/watch?v=Jly4dXapR9c',
  'https://www.youtube.com/watch?v=1AtE54HpXBM',
  'https://www.youtube.com/watch?v=EHV0zs0kVGg',
  'https://www.youtube.com/watch?v=_-jXE-VvZqw',
  'https://www.youtube.com/watch?v=bgS0GPQhzHg',
  'https://www.youtube.com/watch?v=vG8jESHZg_s',
  'https://www.youtube.com/watch?v=OqvD4NC-s9E',
  'https://www.youtube.com/watch?v=_grxnjukBxI',
  'https://www.youtube.com/watch?v=YKRFlNryaWw',
  'https://www.youtube.com/watch?v=a1GeB9y9zzo',
  'https://www.youtube.com/watch?v=75M1XXEZciU',
  'https://www.youtube.com/watch?v=N4x1K97JZG0',
  'https://www.youtube.com/watch?v=NdYmIIbYoH0',
  'https://www.youtube.com/watch?v=YGeFi3Ap61E',
  'https://www.youtube.com/watch?v=NPY5Iq-tCvk',
  'https://www.youtube.com/watch?v=OkSIAlL4f-0',
  'https://www.youtube.com/watch?v=21aXGNHDBWQ',
  'https://www.youtube.com/watch?v=M47Aq3yj_NQ',
  'https://www.youtube.com/watch?v=BS8zi7Dg8TM',
  'https://www.youtube.com/watch?v=ubgR8CKyzYw',
  'https://www.youtube.com/watch?v=C6hmQwfEmzc',
  'https://www.youtube.com/watch?v=yijQXDtxgic',
  'https://www.youtube.com/watch?v=Ruw9fsh3PNY',
  'https://www.youtube.com/watch?v=Tlfd0Y0SjgA',
  'https://www.youtube.com/watch?v=tUuzV9kwSBE',
  'https://www.youtube.com/watch?v=sh0IBg7GBeY',
  'https://www.youtube.com/watch?v=XtadtlSUNQg',
  'https://www.youtube.com/watch?v=OhxXfnLiCbA',
  'https://www.youtube.com/watch?v=j8yAjWvAqyM',
  'https://www.youtube.com/watch?v=hMGHJFVuqpg',
  'https://www.youtube.com/watch?v=bV0tHU04s9E',
  'https://www.youtube.com/watch?v=oNWAiWBup2Q',
  'https://www.youtube.com/watch?v=6kKCbDw7lR4',
  'https://www.youtube.com/watch?v=nl_Cr9lG3Fo',
  'https://www.youtube.com/watch?v=0ZzNlA9uZ0g',
  'https://www.youtube.com/watch?v=KJZLcsAmLbM',
  'https://www.youtube.com/watch?v=dioUiqljTPY',
  'https://www.youtube.com/watch?v=bTyo-dQspJU',
  'https://www.youtube.com/watch?v=w9NFaK4gSe8',
  'https://www.youtube.com/watch?v=pIyrp5Aj7LY',
  'https://www.youtube.com/watch?v=OfUV-F9jFro',
  'https://www.youtube.com/watch?v=3E-C9PipmaA',
  'https://www.youtube.com/watch?v=noT3bA3Ibyk',
  'https://www.youtube.com/watch?v=nXait2wHOQc',
  'https://www.youtube.com/watch?v=X6WHBO_Qc-Q',
  'https://www.youtube.com/watch?v=isBwMtlWLeE',
  'https://www.youtube.com/watch?v=4WdyyPhh4-k',
  'https://www.youtube.com/watch?v=jq_tO6NAlPI',
  'https://www.youtube.com/watch?v=b10LyOeq5Hs',
  'https://www.youtube.com/watch?v=Rp8A7gf0dZ8',
  'https://www.youtube.com/watch?v=d68yRIE9OvQ',
  'https://www.youtube.com/watch?v=ykQ9g2HT2sU',
  'https://www.youtube.com/watch?v=7SB16il97yw',
  'https://www.youtube.com/watch?v=wUVJf2CkNNw',
  'https://www.youtube.com/watch?v=x6FDJAu5yMc',
  'https://www.youtube.com/watch?v=10khF4-1rbU',
  'https://www.youtube.com/watch?v=nom7couJfQg',
  'https://www.youtube.com/watch?v=8D7EY0zKevM',
  'https://www.youtube.com/watch?v=CDTnjLPgMKM',
  'https://www.youtube.com/watch?v=_QKwR14HKf8',
  'https://www.youtube.com/watch?v=qeY1mkXqKgk',
  'https://www.youtube.com/watch?v=4hkg3Zut97U',
]

const op = link => {
  return {
    headers: {
      accept: 'application/json, text/plain, */*',
      'accept-language': 'en,pt-BR;q=0.9,pt;q=0.8,en-US;q=0.7',
      'content-type': 'application/json; charset=UTF-8',
      'sec-ch-ua':
        '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Windows"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-origin',
      'x-auth-token':
        '1JqonNenw9WSm9Sfm5ZsymrDkpqZnmSZyGfHmsZom5OOkJy0spaphNuOrIPUfLm1s4q3i8Gxdrp9',
      'x-requested-domain': 'savesubs.com',
      'x-requested-with': 'xmlhttprequest',
      cookie:
        '_ga=GA1.2.1277732324.1631738455; _gid=GA1.2.920781546.1631933267; _gat=1; __cf_bm=53d22390045a9e68361ca28e7a89a75eea3b7b21-1631934440-0-AY+jvGSDAERnEG9Lxtyr8IzpFwgdTjnJnZh7d+XCkgTvcBoYSdtCG3geO9R0XgyPDfB2c+TUnJTTVkkHjXYfaYDvLMP7etRunAxgpjLVz7JJIZswEnJFmSliAf9gvcSuPg==',
    },
    referrer:
      'https://savesubs.com/process?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DAXGmvZRig88',
    referrerPolicy: 'strict-origin-when-cross-origin',
    body: `{"data":{"url":"${link}"}}`,
    method: 'POST',
    mode: 'cors',
  }
}
const getRep = json => {
  return json.response.formats.length > 0
    ? 'https://savesubs.com' +
        json.response.formats
          .filter(
            v => v.quality === 'English (auto' || v.quality === 'English'
          )[0]
          .url.replace(/,/g, '')
    : ''
}

async function getSubs(link) {
  try {
    const res = await fetch('https://savesubs.com/action/extract', op(link))
    const json = await res.json()
    const hasNoSubTitle = json.message === 'NO_LINKS'
    hasNoSubTitle && console.log('sem legenda')
    if (hasNoSubTitle) return { linkYoutube: link.slice(-11), subsLink: false }

    // console.log({ json, link })
    const retornar = {
      title: json.response.title,
      subsLink: getRep(json),
      linkYoutube: link.slice(-11),
    }
    return retornar
  } catch (error) {
    console.log(error)
    return false
  }
}

let datas = []

function sleep(ms) {
  // console.log('sleep')
  return new Promise(resolve => setTimeout(resolve, ms))
}

for (const [index, filme] of filmes.entries()) {
  const data = await getSubs(filme)
  console.log(
    `${index + 1} / ${filmes.length} / get: ${
      datas.filter(v => v.subsLink).length
    }`
  )
  await sleep(3000)
  data && datas.push(data)
}

console.log('finished 😀')
